import type { StoreBase } from "./store";

// Every mlx-community Gemma 4 instruct variant across the four sizes
// (E2B, E4B, 26B-A4B, 31B) and every quant mlx-community publishes:
// 4bit, 5bit, 6bit, 8bit, mxfp4, mxfp8, bf16. nvfp4 is intentionally
// skipped — it's an NVIDIA FP4 format and can't run on MLX/Apple
// Silicon. Ordered by family size first, then by quant (smallest →
// largest). `base_sha` is the content fingerprint computed by the
// sidecar on first load; we leave it empty here and let the sidecar
// fill it in on load — only adapter-compatibility checks consult it,
// and they compare against the adapter's declared sha, not this list.
export const FALLBACK_BASES: StoreBase[] = [
  // ── E2B (~2B effective) ──────────────────────────────────────────
  {
    base_id: "gemma-4-e2b-it-4bit",
    name: "Gemma 4 E2B Instruct (4-bit)",
    family: "gemma",
    parameters: "E2B",
    quant: "4bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e2b-it-4bit",
    size_bytes: 3_610_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e2b-it-5bit",
    name: "Gemma 4 E2B Instruct (5-bit)",
    family: "gemma",
    parameters: "E2B",
    quant: "5bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e2b-it-5bit",
    size_bytes: 4_190_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e2b-it-mxfp4",
    name: "Gemma 4 E2B Instruct (mxfp4)",
    family: "gemma",
    parameters: "E2B",
    quant: "mxfp4",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e2b-it-mxfp4",
    size_bytes: 4_300_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e2b-it-6bit",
    name: "Gemma 4 E2B Instruct (6-bit)",
    family: "gemma",
    parameters: "E2B",
    quant: "6bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e2b-it-6bit",
    size_bytes: 4_770_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e2b-it-mxfp8",
    name: "Gemma 4 E2B Instruct (mxfp8)",
    family: "gemma",
    parameters: "E2B",
    quant: "mxfp8",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e2b-it-mxfp8",
    size_bytes: 5_790_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e2b-it-8bit",
    name: "Gemma 4 E2B Instruct (8-bit)",
    family: "gemma",
    parameters: "E2B",
    quant: "8bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e2b-it-8bit",
    size_bytes: 5_930_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e2b-it-bf16",
    name: "Gemma 4 E2B Instruct (bf16)",
    family: "gemma",
    parameters: "E2B",
    quant: "bf16",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e2b-it-bf16",
    size_bytes: 10_280_000_000,
    license: "Gemma Terms",
    description: "",
  },
  // ── E4B (~4B effective) ──────────────────────────────────────────
  {
    base_id: "gemma-4-e4b-it-4bit",
    name: "Gemma 4 E4B Instruct (4-bit)",
    family: "gemma",
    parameters: "E4B",
    quant: "4bit",
    base_sha: "769bec7273285355f6ba44a974df0e223fa7db7e3267e86b3e032ff006f792bc",
    hf_repo: "mlx-community/gemma-4-e4b-it-4bit",
    size_bytes: 5_250_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e4b-it-5bit",
    name: "Gemma 4 E4B Instruct (5-bit)",
    family: "gemma",
    parameters: "E4B",
    quant: "5bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e4b-it-5bit",
    size_bytes: 6_190_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e4b-it-mxfp4",
    name: "Gemma 4 E4B Instruct (mxfp4)",
    family: "gemma",
    parameters: "E4B",
    quant: "mxfp4",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e4b-it-mxfp4",
    size_bytes: 6_770_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e4b-it-6bit",
    name: "Gemma 4 E4B Instruct (6-bit)",
    family: "gemma",
    parameters: "E4B",
    quant: "6bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e4b-it-6bit",
    size_bytes: 7_120_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e4b-it-mxfp8",
    name: "Gemma 4 E4B Instruct (mxfp8)",
    family: "gemma",
    parameters: "E4B",
    quant: "mxfp8",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e4b-it-mxfp8",
    size_bytes: 8_760_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e4b-it-8bit",
    name: "Gemma 4 E4B Instruct (8-bit)",
    family: "gemma",
    parameters: "E4B",
    quant: "8bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e4b-it-8bit",
    size_bytes: 9_000_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-e4b-it-bf16",
    name: "Gemma 4 E4B Instruct (bf16)",
    family: "gemma",
    parameters: "E4B",
    quant: "bf16",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-e4b-it-bf16",
    size_bytes: 16_020_000_000,
    license: "Gemma Terms",
    description: "",
  },
  // ── 26B-A4B (26B total, ~4B active; MoE) ─────────────────────────
  {
    base_id: "gemma-4-26b-a4b-it-mxfp4",
    name: "Gemma 4 26B-A4B Instruct (mxfp4)",
    family: "gemma",
    parameters: "26B-A4B",
    quant: "mxfp4",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-26b-a4b-it-mxfp4",
    size_bytes: 29_420_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-26b-a4b-it-8bit",
    name: "Gemma 4 26B-A4B Instruct (8-bit)",
    family: "gemma",
    parameters: "26B-A4B",
    quant: "8bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-26b-a4b-it-8bit",
    size_bytes: 27_990_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-26b-a4b-it-4bit",
    name: "Gemma 4 26B-A4B Instruct (4-bit)",
    family: "gemma",
    parameters: "26B-A4B",
    quant: "4bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-26b-a4b-it-4bit",
    size_bytes: 30_980_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-26b-a4b-it-5bit",
    name: "Gemma 4 26B-A4B Instruct (5-bit)",
    family: "gemma",
    parameters: "26B-A4B",
    quant: "5bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-26b-a4b-it-5bit",
    size_bytes: 37_220_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-26b-a4b-it-6bit",
    name: "Gemma 4 26B-A4B Instruct (6-bit)",
    family: "gemma",
    parameters: "26B-A4B",
    quant: "6bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-26b-a4b-it-6bit",
    size_bytes: 43_460_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-26b-a4b-it-bf16",
    name: "Gemma 4 26B-A4B Instruct (bf16)",
    family: "gemma",
    parameters: "26B-A4B",
    quant: "bf16",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-26b-a4b-it-bf16",
    size_bytes: 51_640_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-26b-a4b-it-mxfp8",
    name: "Gemma 4 26B-A4B Instruct (mxfp8)",
    family: "gemma",
    parameters: "26B-A4B",
    quant: "mxfp8",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-26b-a4b-it-mxfp8",
    size_bytes: 53_860_000_000,
    license: "Gemma Terms",
    description: "",
  },
  // ── 31B (dense) ──────────────────────────────────────────────────
  {
    base_id: "gemma-4-31b-it-mxfp4",
    name: "Gemma 4 31B Instruct (mxfp4)",
    family: "gemma",
    parameters: "31B",
    quant: "mxfp4",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-31b-it-mxfp4",
    size_bytes: 17_480_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-31b-it-5bit",
    name: "Gemma 4 31B Instruct (5-bit)",
    family: "gemma",
    parameters: "31B",
    quant: "5bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-31b-it-5bit",
    size_bytes: 22_280_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-31b-it-6bit",
    name: "Gemma 4 31B Instruct (6-bit)",
    family: "gemma",
    parameters: "31B",
    quant: "6bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-31b-it-6bit",
    size_bytes: 26_120_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-31b-it-mxfp8",
    name: "Gemma 4 31B Instruct (mxfp8)",
    family: "gemma",
    parameters: "31B",
    quant: "mxfp8",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-31b-it-mxfp8",
    size_bytes: 32_840_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-31b-it-8bit",
    name: "Gemma 4 31B Instruct (8-bit)",
    family: "gemma",
    parameters: "31B",
    quant: "8bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-31b-it-8bit",
    size_bytes: 33_800_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-31b-it-4bit",
    name: "Gemma 4 31B Instruct (4-bit)",
    family: "gemma",
    parameters: "31B",
    quant: "4bit",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-31b-it-4bit",
    size_bytes: 36_860_000_000,
    license: "Gemma Terms",
    description: "",
  },
  {
    base_id: "gemma-4-31b-it-bf16",
    name: "Gemma 4 31B Instruct (bf16)",
    family: "gemma",
    parameters: "31B",
    quant: "bf16",
    base_sha: "",
    hf_repo: "mlx-community/gemma-4-31b-it-bf16",
    size_bytes: 62_580_000_000,
    license: "Gemma Terms",
    description: "",
  },
];
